### PR TITLE
Enable Navie in the user interface

### PR DESCRIPTION
**Pull request by jansorg**
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/533

This PR makes Navie available to users.

The AppMap CLI processes are restarted when the API key changes. The indexer JSON-RPC service needs an up-to-date API key to provide valid responses for the Navie webview.

If an editor is opened and text is selected, then this text is taken as default value for Navie's question text input.
If an editor is opened, then the editor's file is used as context to locate the matching appmap.yml file and the matching AppMap indexer JSON-RPC service.

Each execution of the "Explain with AppMap" action opens a new Navie webview.

Notification when Navie is not ready yet. We could change it to a modal message box instead of a notification:
image

Navie tab:
image

Popup if there's more than one AppMap indexer available:
Screenshot_20240125_124758

### CODE REVIEW

**Review by ahtrotta — CHANGES_REQUESTED** [review]
There are some small hiccups that I'd like you to investigate. It's possible these are on our end, but I haven't seen them happen before. These were found when using `2023.1.1` with the `spring-petclinic` project.

When trying to use the select menu for AppMap search results, it doesn't always render correctly:

image

This also happens when using the select menu for selected code objects:

image

In the AppMap in the Navie webview, the `Dependency Map` is blank, and when the AppMap first loads, the zoom controls are rendered incorrectly:

image

**Comment by jansorg** [comment]
@ahtrotta I've rebased on develop and also updated the navie components to the latest version.
I'm not sure what I could do about the rendering issues. Unless it's somehow caused by the plugin's index.html and/or the init of the JS application, it's all inside the webview and out of the plugin's control. It may be problems with the JCEF webkit integration, but that usually not fixable for plugins.

The dependency view and data is managed by the webview itself, AFAIK. The indexer's JSON-RPC service is most likely providing the data needed for the view. Or it there a property I need to pass to the navie webview?

**Comment by ahtrotta** [comment]
> @ahtrotta I've rebased on develop and also updated the navie components to the latest version. I'm not sure what I could do about the rendering issues. Unless it's somehow caused by the plugin's index.html and/or the init of the JS application, it's all inside the webview and out of the plugin's control. It may be problems with the JCEF webkit integration, but that usually not fixable for plugins.

I haven't seen the select menu rendering issues happen since the first time, and it's not a blocking issue anyway, so we can call this resolved.

> The dependency view and data is managed by the webview itself, AFAIK. The indexer's JSON-RPC service is most likely providing the data needed for the view. Or it there a property I need to pass to the navie webview?

I managed to track this down to a missing import and I pushed a fix for it.

**Review by ahtrotta — CHANGES_REQUESTED** [review]
This is working pretty well, thanks!

An issue that I found that needs to be resolved is when there are multiple `appmap.yml` files within a module then we need to have the user select which index process they want to use for `AppMap Explain`. For example, in the screenshot below, there are a total of three `appmap.yml` files, and there is an index process associated with each, but the user is only prompted with a menu showing two options. We need to have a menu with three options here:

image

For the relevant changes in VS Code, see [this commit](https://github.com/getappmap/vscode-appland/pull/872/commits/0f371fe3d6756d55725c57fa94547a548c64c337).

**Comment by ahtrotta** [comment]
@jansorg since we just updated `@appland/components` again, can you rebase this?

**Comment by ahtrotta** [comment]
I've found an issue. If I have multiple `appmap.yml` files in a module and then I open Navie, I get the expected selection menu:

image

However, if I close Navie, keep the same selection in the project file explorer menu (`MysqlTestApplication` in the screenshot), and then re-open Navie, then I don't get selection menu and it doesn't remember my previous choice.

We should make it so that every time Navie is opened the user should see the selection menu.

**Comment by ahtrotta** [comment]
@jansorg I found another issue. If I delete an `appmap.yml` the indexer process is not terminated and when I open Navie, I still get the selection menu even if there is only one `appmap.yml` left in the project.

**Comment by ahtrotta** [comment]
@jansorg I found a major problem. When using `2022.3`, it is not possible to close and re-open an AppMap multiple times. It will lead to a `404` error.

image

**Review by ahtrotta — APPROVED** [review]
This is working well, thanks!

The only small problem I'm noticing now is that when a user clicks the export button in a sequence diagram, they get this menu:

image


But we haven't implemented the `JSON` option yet. I don't think this should hold up this feature, but it's worth noting.

**Comment by jansorg** [comment]
@ahtrotta Thanks for the review! Please feel free to merge this when you're happy with it.

**Pull request merged**
