### PR TITLE
Support "Delete AppMaps" and "Delete all AppMaps" in the AppMap toolwindow

### PR DESCRIPTION
**Pull request by jansorg**
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/465

This PR
- adds a context menu to the AppMap panel in the AppMap toolwindow
  - Action "Delete selected AppMaps...", relying on the SDK's delete implementation for one or multiple files
  - Action "Delete all AppMaps...", relying on the SDK's delete implementation for one or multiple files
  - Action "Jump to source", reusing the implementation of the SDK
  - Action "Expand All", reusing the implementation of the SDK
  - Action "Collapse AlL", reusing the implementation of the SDK

This isn't testable in a good way, because
- we're reusing Actions of the SDK (which hopefully have test coverage already)
- the Actions interact with the user using UI dialogs. Tests are run in a headless environment and can't use dialogs

Screenshot_20231005_194748

### CODE REVIEW

**Comment by ahtrotta** [comment]
Thanks for this PR @jansorg! Can you get the build to pass before I review it?

**Comment by jansorg** [comment]
Tests are failing due to a bug in the latest version of the AppMap agent. I'll restart test when the agent is fixed.

**Comment by dividedmind** [comment]
> Tests are failing due to a bug in the latest version of the AppMap agent. I'll restart test when the agent is fixed.

What's the bug?

**Comment by jansorg** [comment]
> > Tests are failing due to a bug in the latest version of the AppMap agent. I'll restart test when the agent is fixed.
> 
> What's the bug?

https://github.com/getappmap/appmap-intellij-plugin/actions/runs/6422578059/job/17491063784?pr=467#step:7:144, reported on Slack

**Comment by ahtrotta** [comment]
I just tried this out and it mostly works well, but when I did the `Delete all AppMaps` option it left a bunch of metadata files in the `junit` folder. Interestingly, it deleted the metadata files in the `remote` and `request_recording` folders. Can you update this so that it consistently deletes metadata folders?

**Review by ahtrotta — APPROVED** [review]
Looks good and works well, thanks!

**Comment by jansorg** [comment]
@ahtrotta I pushed a commit to remove AppMap  index data when a *.appmap.json file is deleted.

**Review by ahtrotta — APPROVED** [review]
Looks good, thanks @jansorg!

**Pull request merged**
