### PR TITLE
Update Readme and Marketplace description

### PR DESCRIPTION
**Pull request by jansorg**
This PR corrects the minimum required version and a few minor things.

- [ ] Should it mention JUnit?
- [ ] Is the list of supported web applications and frameworks still up-to-date?

### CODE REVIEW

**Comment by brikelly** [comment]
@jansorg it looks like this branch has many commits on it unrelated to the original change. Perhaps it was rebased incorrectly or something? Either way, it's not going to be easy to review. Can you either clean it up or close it and create a new PR?

**Comment by jansorg** [comment]
There was just one commit, I‘m not sure what happened to „develop“.

**Comment by jansorg** [comment]
@brikelly I've rebased, please try again.

**Review by brikelly — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
