### PR TITLE
Execute webview callbacks in a background thread to avoid UI freezes on macOS

### PR DESCRIPTION
**Pull request by jansorg**
The handlers of messages posted from webview to IDE host are handled outside the EDT (the UI dispatch thread).
- On Linux, it's a regular background thread
- On macOS, it's `AWT-AppKit`, which is the thread handling native UI integration AFAIK.

On macOS, it happened that the EDT executed a WriteAction and a message handler of the Installation Guide webview on a ReadAction on thread `AWT-AppKit`. The handling on the EDT involved waiting on `AWT-AppKit`, which led to a deadlock.

This pull requests
1. refactors `InstallGuideEditor` to use our abstraction `WebviewEditor`. The other webviews were already using it and the install guide editor was the remaining implementation
2. refactors `WebviewEditor` to always execute webview message handlers in a background thread, which is not the calling thread of the handler, i.e. outside of `AWT-AppKit` on macOS

Thread dumps:
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@789a637e
	at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.13/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.13/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	at java.desktop@11.0.13/sun.awt.AWTThreading.execute(AWTThreading.java:147)
	at java.desktop@11.0.13/sun.awt.AWTThreading.executeWaitToolkit(AWTThreading.java:80)
	at java.desktop@11.0.13/sun.awt.AWTThreading.executeWaitToolkit(AWTThreading.java:53)
	at java.desktop@11.0.13/sun.awt.AWTThreading.executeWaitToolkit(AWTThreading.java:63)
	at java.desktop@11.0.13/sun.lwawt.macosx.CPlatformWindow.lambda$setVisible$10(CPlatformWindow.java:765)
	at java.desktop@11.0.13/sun.lwawt.macosx.CPlatformWindow$$Lambda$1187/0x0000000800cddc40.run(Unknown Source)
	at java.desktop@11.0.13/sun.lwawt.macosx.CFRetainedResource.execute(CFRetainedResource.java:134)
	at java.desktop@11.0.13/sun.lwawt.macosx.CPlatformWindow.setVisible(CPlatformWindow.java:765)
	at java.desktop@11.0.13/sun.lwawt.LWWindowPeer.setVisibleImpl(LWWindowPeer.java:286)
	at java.desktop@11.0.13/sun.lwawt.LWComponentPeer.setVisible(LWComponentPeer.java:779)
	at java.desktop@11.0.13/java.awt.Component.hide(Component.java:1769)
	at java.desktop@11.0.13/java.awt.Window.hide(Window.java:1143)
	at java.desktop@11.0.13/java.awt.Window$1DisposeAction.run(Window.java:1216)
	at java.desktop@11.0.13/java.awt.Window.doDispose(Window.java:1234)
	at java.desktop@11.0.13/java.awt.Window.dispose(Window.java:1175)
	at com.intellij.ui.jcef.HwFacadeHelper.removeNotify(HwFacadeHelper.java:221)
	at com.intellij.ui.jcef.HwFacadeJPanel.removeNotify(HwFacadeJPanel.java:25)
	at com.intellij.ui.BalloonImpl$MyComponent.removeNotify(BalloonImpl.java:1952)
	at java.desktop@11.0.13/java.awt.Container.remove(Container.java:1231)
	at java.desktop@11.0.13/javax.swing.JLayeredPane.remove(JLayeredPane.java:252)
	at java.desktop@11.0.13/java.awt.Container.remove(Container.java:1289)
	at com.intellij.ui.BalloonImpl.hideAndDispose(BalloonImpl.java:1090)
	at com.intellij.ui.BalloonImpl.dispose(BalloonImpl.java:1049)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:139)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:169)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:217)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:205)
	at com.intellij.ui.popup.BalloonPopupBuilderImpl.lambda$createBalloon$0(BalloonPopupBuilderImpl.java:285)
	at com.intellij.ui.popup.BalloonPopupBuilderImpl$$Lambda$1835/0x00000008011c4840.dispose(Unknown Source)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:139)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:169)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:217)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:205)
	at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel.removeProgress(InfoAndProgressPanel.java:295)
	at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel$MyInlineProgressIndicator.lambda$finish$4(InfoAndProgressPanel.java:723)
	at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel$MyInlineProgressIndicator$$Lambda$2819/0x00000008017ccc40.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$407/0x00000008004cb840.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop@11.0.13/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.13/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop@11.0.13/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.13/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.13/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.13/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.13/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.ide.IdeEventQueue$$Lambda$442/0x000000080052dc40.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.ide.IdeEventQueue$$Lambda$441/0x000000080052ec40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)


"AWT-AppKit" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on java.util.concurrent.CompletableFuture$Signaller@2e420119
	at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.13/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
	at java.base@11.0.13/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.13/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	at java.base@11.0.13/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
	at com.intellij.openapi.progress.impl.ProgressRunner.waitForFutureUnlockingThread(ProgressRunner.java:406)
	at com.intellij.openapi.progress.impl.ProgressRunner.normalExec(ProgressRunner.java:392)
	at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:262)
	at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:553)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:265)
	at appland.installGuide.projectData.DefaultProjectDataService.updateMetadata(DefaultProjectDataService.java:51)
	at appland.installGuide.projectData.DefaultProjectDataService.getAppMapProjects(DefaultProjectDataService.java:46)
	at appland.installGuide.InstallGuideEditor.findProjects(InstallGuideEditor.java:389)
	at appland.installGuide.InstallGuideEditor.lambda$onJavaScriptApplicationReady$6(InstallGuideEditor.java:228)
	at appland.installGuide.InstallGuideEditor$$Lambda$3165/0x000000080195a440.apply(Unknown Source)
	at com.intellij.ui.jcef.JBCefJSQuery$1.onQuery(JBCefJSQuery.java:118)

```

### CODE REVIEW

**Comment by kgilpin** [comment]
Can you add a test for this so it doesn't get accidentally reverted?

**Comment by jansorg** [comment]
@kgilpin I'll check if there's perhaps a way to test at least the thread used to execute the callbacks. UI-testing the webview interaction isn't possible without spending a lot of time, I think.

**Comment by kgilpin** [comment]
I agree about the UI test, that would be too much work to just verify the fix. But if there is some way to assert that the fix you've applied is in place, that will prevent a future regression.

**Comment by jansorg** [comment]
I attempted to add  a test, but the JCEF integration doesn't work well (so far) in the headless test environment. I logged my results at https://github.com/getappmap/appmap-intellij-plugin/issues/378. I'll ask on the JetBrains slack if there's a way to make this work. 
I suggest that this PR is merged regardless. I'll track progress on tests in the issue linked above.

**Review by ahtrotta — APPROVED** [review]

**Pull request merged**
