### PR TITLE
Migration from appland.com to appmap.io and update Github URL

### PR DESCRIPTION
**Pull request by petecheslock**
We have setup permanent redirects for our domain on appland.com -> appmap.io.

### CODE REVIEW

**Comment by petecheslock** [comment]
@jansorg I'm not sure how to confirm those large diffs - or test them.  They are basically from the output of search/replace from "appland.com" to "appmap.io" so they _should_ be safe.

**Comment by jansorg** [comment]
@petecheslock You can safely ignore all files under `src/test/data`. These files are only used for our tests. Do you have an easy way to revert just the changes inside this dir? I think that would make this PR a bit easier to read.

**Review by jansorg — CHANGES_REQUESTED** [review]
I think most of this is fine.
Many changes are in the bundled JS sources. Updating to a new version of the JS component, which already have the new URLs would be better, I think.
I don't trust search and replace inside minified sources...

If the new version also carries other, incompatible changes, then we may have to go with search-and-replace.

Reverting changes inside `src/test/data` would make this PR a bit smaller. It's only generated data.

**Comment by petecheslock** [comment]
I can go and pull out the changes within those directories to make this more manageable.

**Comment by petecheslock** [comment]
ok - @jansorg i've pulled out changes to files in `src/test/data` which makes the PR much simpler.

**Comment by petecheslock** [comment]
Also here is the PR i created for the appmap-js project.  https://github.com/getappmap/appmap-js/pull/740

**Comment by jansorg** [comment]
Unless this PR is urgent, I'd prefer to wait for https://github.com/getappmap/appmap-js/pull/740, because that more reliable than search&replace in minified sources.

**Comment by petecheslock** [comment]
@jansorg it's merged now should be good to go.

**Review by jansorg — APPROVED** [review]
Seems fine to me. I briefly tested the webview JS applications and couldn't find an issue with the URLs.
I'd prefer to just link to updates JS applications via `package.json`, but that's not possible without introduction possible issues, because only newer versions are available with the updated URLs. Let's merge now and update the JS applications in new PRs.

I pushed a commit to fix two failing tests.

**Pull request merged**
