### PR TITLE
Allow users to specify their own OpenAI key in the settings

### PR DESCRIPTION
**Pull request by jansorg**
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/675

This PR adds a new setting to configure a custom OpenAI key.
There's currently no additonal action (e.g. `AppMap: Set OpenAPI key`), but it could be added if it's needed.

Settings are persisted in the IDE's password safe.

When the OpenAI key changed, a notification is displayed in each open project to allow the user to reload it. 
The application-wide JSON-RPC process **is NOT restarted** immediately after the change of the OpenAI key. A restart would invalidate the port used by open Navie webviews.

The notification is sticky, which means that it won't hide automatically. Otherwise the user might miss the required reload.

This PR is moving `applyServiceEnvironment` from the application settings class to the command line handler class, because it's now using both ApplicationSettings and the new `SecureApplicationSettings`.

https://github.com/getappmap/appmap-intellij-plugin/pull/628 is needed, because "Reopen project" added by this PR is triggering the bug fixed by #628 .

**Testing**:
- I've tested this on Linux and macOS Sonoma with the secure storage of the OpenAI key. I haven't seen any weird prompts or behavior.

Updated settings UI:
image

Notification:
image

### CODE REVIEW

**Comment by kgilpin** [comment]
If the RPC process is restarted, then why does the user need to restart JetBrains?

**Comment by kgilpin** [comment]
> macOS because the OS's password access confirmation was blocking IDE startup.

do you have more information on this? We are using a facility provided by JetBrains and it results in the IDE being blocked from starting?

**Comment by jansorg** [comment]
> If the RPC process is restarted, then why does the user need to restart JetBrains?

I understood that all webview editors and also the JSON-RPC process need to be restarted. If it's only the process, then I could implement it that way.

**Comment by kgilpin** [comment]
> > If the RPC process is restarted, then why does the user need to restart JetBrains?
> 
> I understood that all webview editors and also the JSON-RPC process need to be restarted. If it's only the process, then I could implement it that way.

You’re right because the RPC ports are out of date and I don’t think they can be updated. 

We can work on that in a future version.

**Comment by jansorg** [comment]
> > > macOS because the OS's password access confirmation was blocking IDE startup.
> > 
> > 
> > do you have more information on this? We are using a facility provided by JetBrains and it results in the IDE being blocked from starting?
> 
> I'd need to test this with the current IDEs. I think it was caused by requesting secure storage during startup, but I'm not sure if that's still happening.

I tested on macOS Sonoma and it worked well.

**Comment by jansorg** [comment]
I've made a few changes to the first version of this PR:
- after a change of the key, the JSON-RPC is NOT restarted. It would invalidate the key
- the notification does not contain an action to reload the project

**Comment by ahtrotta** [comment]
@jansorg can you look into the build failure?

**Comment by jansorg** [comment]
@ahtrotta It was a flaky test. I restarted the tests.
The unstable test which will hopefully and finally be fixed by https://github.com/getappmap/appmap-intellij-plugin/pull/674.

**Review by ahtrotta — APPROVED** [review]
Looks good and worked well when I tested it manually, thanks!

**Pull request merged**
