### PR TITLE
Execute GitHub Actions on Windows and macOS

### LINKED ISSUE #261: JetBrains builds are tested on Windows

### PR DESCRIPTION
**Pull request by jansorg**
Closes #261  

This adds CI support for Windows and macOS using GitHub Actions.

- I added a few fixes to our tests to successfully run on Windows. Some test errors only happened, because of (apparently) dramatically slower Windows machines, e.g. background thread activity long after a project was disposed by a test.
- With the default platform version tests on Windows failed. The AppMap CLI processes failed to terminate and continued to run. The running processes locked the `tmp/appmap` dir, which then prevented to successfully terminate and cleanup tests using AppMap data. I wasn't able to reproduce or to find a working fix. Building against a later JetBrains platform version worked, though. My assumption is, that the later SDKs fixed process termination on Windows.
- I manually verified that the AppMap CLI processes are terminated on Windows with 2021.2 when a project is closed. It's still possible that the above error of failing process termination is also present for Windows users, but so far it seems only limited to our tests and/or Windows via GitHub Actions.
- I also observed GH actions workflow executions, which did not finish. I limited the execution time to 45 minutes to terminate early. Updating to latest Gradle wasn't possible because of https://github.com/gradle/gradle/issues/25752

It also helped to find and fix a real bug:
- https://github.com/getappmap/appmap-intellij-plugin/pull/401/commits/6c04a3c95625f4227288a229a21ed82658bced41 fixed the update of `appmap_dir:`. Previously, the Windows file separator was used instead of `/` on all platforms.

Stack from a hung workflow: https://github.com/getappmap/appmap-intellij-plugin/actions/runs/6125286203/job/16626940066
```
"main" #1 prio=5 os_prio=0 cpu=4812.50ms elapsed=1213.11s tid=0x000001c8183732b0 nid=0x620 runnable  [0x00000092d0dfc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WEPoll.wait(java.base@17.0.8.1/Native Method)
	at sun.nio.ch.WEPollSelectorImpl.doSelect(java.base@17.0.8.1/WEPollSelectorImpl.java:111)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@17.0.8.1/SelectorImpl.java:129)
	- locked <0x00000000fc8aa5d0> (a sun.nio.ch.Util$2)
	- locked <0x00000000fc8aa3d8> (a sun.nio.ch.WEPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@17.0.8.1/SelectorImpl.java:146)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:185)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:355)
	at com.esotericsoftware.kryo.io.Input.readInt(Input.java:350)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readSmallInt(KryoBackedDecoder.java:133)
	at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:155)
	at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:77)
	at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:35)
	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:235)
	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:204)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:167)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:210)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:259)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:230)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:96)
	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:[361](https://github.com/getappmap/appmap-intellij-plugin/actions/runs/6125286203/job/16626940066#step:7:362))
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.8.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.8.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.8.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.8.1/Method.java:568)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.8.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.8.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.8.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.8.1/Method.java:568)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.8.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.8.1/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.8.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.8.1/Method.java:568)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:110)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:66)
```

### CODE REVIEW

**Comment by jansorg** [comment]
The Travis build failed, but AFAIK it's unrelated to this PR. https://github.com/getappmap/appmap-intellij-plugin/runs/16676399119

**Comment by jansorg** [comment]
> Also, can you clean up the history, please? At the very least, the three commits that touch `build.yml` should probably be combined.

I've cleaned up the history and squashed the commits into more meaningful commits.

> @jansorg Travis builds for both `master` and `develop` currently run ok, so this failure seems worth investigating. Can you see if you can figure out what's going on, please?

The error is caused by a failed download from the JetBrains CDN. This is failing for this PR, but working in others. I'm unsure how this PR could have caused this, but I'll investigate. I suspect that it's caused by a Travis cache and/or a certain Travis runner, but that's a wild guess.

```
> Task :runPluginVerifier
[gradle-intellij-plugin :runPluginVerifier] Cannot download 'IC-2021.3.3' from 'release' channel: https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/ideaIC-2021.3.3.tar.gz. Run with --debug option to get more log output.
Starting the IntelliJ Plugin Verifier 1.304
Verification reports directory: /home/travis/build/getappmap/appmap-intellij-plugin/build/reports/pluginVerifier
2023-09-15T14:26:15 [main] INFO  verification - Reading IDE /home/travis/.cache/pluginVerifier/ides/IC-2021.3.3
2023-09-15T14:26:15 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /home/travis/.cache/pluginVerifier/ides/IC-2021.3.3
Exception in thread "main" com.jetbrains.plugin.structure.ide.InvalidIdeException: IDE by path '/home/travis/.cache/pluginVerifier/ides/IC-2021.3.3' is invalid: IDE directory content is invalid
	at com.jetbrains.plugin.structure.ide.IdeManagerImpl.createIde(IdeManagerImpl.kt:34)
	at com.jetbrains.plugin.structure.ide.IdeManagerImpl.createIde(IdeManagerImpl.kt:25)
	at com.jetbrains.pluginverifier.ide.IdeDescriptor$Companion.create(IdeDescriptor.kt:59)
	at com.jetbrains.pluginverifier.options.OptionsParser.createIdeDescriptor(OptionsParser.kt:112)
	at com.jetbrains.pluginverifier.options.OptionsParser.createIdeDescriptor(OptionsParser.kt:107)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.DefaultIdeDescriptorParser.parseIdeDescriptors(CheckPluginParamsBuilder.kt:125)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginParamsBuilder.build(CheckPluginParamsBuilder.kt:41)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginParamsBuilder.build(CheckPluginParamsBuilder.kt:27)
	at com.jetbrains.pluginverifier.PluginVerifierMain.main(PluginVerifierMain.kt:127)
[gradle-intellij-plugin :runPluginVerifier] Error during Plugin Verifier CLI execution:
Starting the IntelliJ Plugin Verifier 1.304
Verification reports directory: /home/travis/build/getappmap/appmap-intellij-plugin/build/reports/pluginVerifier
2023-09-15T14:26:15 [main] INFO  verification - Reading IDE /home/travis/.cache/pluginVerifier/ides/IC-2021.3.3
2023-09-15T14:26:15 [main] INFO  c.j.p.options.OptionsParser - Reading IDE from /home/travis/.cache/pluginVerifier/ides/IC-2021.3.3
```

**Comment by jansorg** [comment]
Travis CI is green now, after rerunning it without other changes. Most likely it was caused by a network issue of the JetBrains CDN or of the Travis machine.

**Review by apotterri — APPROVED** [review]
Thanks for persevering with the investigation into the build failure. Glad it was just an intermittent problem, I guess. ;)

Thanks, too, for the history cleanup. It's fine for now. In the future, if you can keep your commit subject lines to fewer than 50 characters, it will avoid this:
image

**Pull request merged**
