### PR TITLE
Replace .form UI files with Kotlin UI DSL v2

### PR DESCRIPTION
**Pull request by jansorg**
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/548

Replaces the .form files with UI DSL v2. Support for .form files is deprecated and mostly unmaintained by JetBrains now.

Previously, code instrumentation via the IntelliJ Gradle plugin was used to create .class files from the JetBrains .form files. Instrumentation is not needed anymore and is disabled by this PR.

UI DSL v2 needs Kotlin. This PR enables Kotlin to allow writing the UI DSL code, but everything else is going to remain Java source code.

Unfortunately, the UI DSL isn't backwards compatible in a few places. We're dropping support for 2021.3 to fix this.

Settings:
image

Start AppMap recording:
image

Stop AppMap recording:
image

### CODE REVIEW

**Review by ahtrotta — CHANGES_REQUESTED** [review]
When I run the plugin locally, I get this warning related to this change:

```
> Task :plugin-core:compileKotlin
w: Lombok Kotlin compiler plugin is an experimental feature. See: https://kotlinlang.org/docs/components-stability.html.
w: file:///home/ahtrotta/projects/appmap/appmap-intellij-plugin/plugin-core/src/main/kotlin/appland/remote/StartRemoteRecordingForm.kt:22:22 'horizontalAlign(HorizontalAlign): Cell<T>' is deprecated. Use align(AlignX.LEFT/CENTER/RIGHT/FILL) method instead
w: file:///home/ahtrotta/projects/appmap/appmap-intellij-plugin/plugin-core/src/main/kotlin/appland/remote/StopRemoteRecordingForm.kt:18:60 'horizontalAlign(HorizontalAlign): Cell<T>' is deprecated. Use align(AlignX.LEFT/CENTER/RIGHT/FILL) method instead
w: file:///home/ahtrotta/projects/appmap/appmap-intellij-plugin/plugin-core/src/main/kotlin/appland/remote/StopRemoteRecordingForm.kt:25:43 'horizontalAlign(HorizontalAlign): Cell<T>' is deprecated. Use align(AlignX.LEFT/CENTER/RIGHT/FILL) method instead
```

Could you address this? Thanks!

**Comment by jansorg** [comment]
@ahtrotta Is it possible that you were compiling for a later SDK? 
I'm not seeing these warnings with the default platform version, but I know that later versions added deprecations like this.

**Comment by ahtrotta** [comment]
> @ahtrotta Is it possible that you were compiling for a later SDK? I'm not seeing these warnings with the default platform version, but I know that later versions added deprecations like this.

Yeah I was using 2023.3.2

**Comment by ahtrotta** [comment]
@jansorg what is the status of this PR?

**Comment by jansorg** [comment]
There's a flaky test, but only on CI. I'll fix it soon.
It's not a user-visible change, so it's not important for UX/UI testing.

**Comment by ahtrotta** [comment]
> There's a flaky test, but only on CI. I'll fix it soon. It's not a user-visible change, so it's not important for UX/UI testing.

Thanks for the update! I was just wondering because the issue is in the `In Review` column on the board but it's marked as a draft PR. I'll move the issue to `In Progress`.

**Comment by jansorg** [comment]
Oh, sorry! I thought it was ready, but missed the test.

**Comment by jansorg** [comment]
> When I run the plugin locally, I get this warning related to this change:
> 
> ```
> > Task :plugin-core:compileKotlin
> w: Lombok Kotlin compiler plugin is an experimental feature. See: https://kotlinlang.org/docs/components-stability.html.
> w: file:///home/ahtrotta/projects/appmap/appmap-intellij-plugin/plugin-core/src/main/kotlin/appland/remote/StartRemoteRecordingForm.kt:22:22 'horizontalAlign(HorizontalAlign): Cell<T>' is deprecated. Use align(AlignX.LEFT/CENTER/RIGHT/FILL) method instead
> w: file:///home/ahtrotta/projects/appmap/appmap-intellij-plugin/plugin-core/src/main/kotlin/appland/remote/StopRemoteRecordingForm.kt:18:60 'horizontalAlign(HorizontalAlign): Cell<T>' is deprecated. Use align(AlignX.LEFT/CENTER/RIGHT/FILL) method instead
> w: file:///home/ahtrotta/projects/appmap/appmap-intellij-plugin/plugin-core/src/main/kotlin/appland/remote/StopRemoteRecordingForm.kt:25:43 'horizontalAlign(HorizontalAlign): Cell<T>' is deprecated. Use align(AlignX.LEFT/CENTER/RIGHT/FILL) method instead
> ```
> 
> Could you address this? Thanks!

@ahtrotta I've fixed the test, this PR is ready for review now.
Because the above API was only added in a later version of the SDK, we're unable to fix it.

**Comment by ahtrotta** [comment]
> @ahtrotta I've fixed the test, this PR is ready for review now. Because the above API was only added in a later version of the SDK, we're unable to fix it.

Okay, great I'll take a look!

**Review by ahtrotta — APPROVED** [review]

**Pull request merged**
