### PR TITLE
Implement tree view for runtime analysis

### PR DESCRIPTION
**Pull request by jansorg**
Closes https://github.com/getappmap/appmap-intellij-plugin/issues/328

Updates the tree of the "Runtime Analysis" panel to display a hierarchy of findings and AppMaps.

- Findings of failed tests are not displayed in the  "Findings" group.

Questions/Unsolved issues:
- [x] Do I have to deduplicate findings before applying the grouping or only the findings inside a single rule group?
- [x] ~~https://github.com/getappmap/appmap-intellij-plugin/issues/328#issuecomment-1682423415 Should I add the additional group inside "Failed tests"?~~
- [ ] If no items are available, the empty panel is no displayed. I'd like to implement this in another PR because this PR is already large.
- [x] I couldn't find matching icons for the impact domain nodes and the rule groups in the set of predefined icons

image

### CODE REVIEW

**Comment by ahtrotta** [comment]
> Questions/Unsolved issues:
> 
> * [ ]  Do I have to deduplicate findings before applying the grouping or only the findings inside a single rule group?

Either way should be fine as long as you're using `hash_v2` to de-duplicate. How is it implemented currently?

> * [ ]  ["Runtime Analysis panel" should display a tree #328 (comment)](https://github.com/getappmap/appmap-intellij-plugin/issues/328#issuecomment-1682423415) Should I add the additional group inside "Failed tests"?

The `failed tests` group in VS Code is for the `AppMap` toolbar, not the `Runtime Analysis` toolbar, so I think this should be implemented in a separate batch of work.

> * [ ]  If no items are available, the empty panel is no displayed. I'd like to implement this in another PR because this PR is already large.

That's fine, it can be a separate PR.

> * [ ]  I couldn't find matching icons for the impact domain nodes and the rule groups in the set of predefined icons

That's fine, if we think it's a problem we can address this later.

**Review by ahtrotta — CHANGES_REQUESTED** [review]
I'm having an issue with this branch. If I setup a fresh copy of `sample_app_6th_ed` by cloning [this repo](https://github.com/land-of-apps/sample_app_6th_ed) (using node `v14.21.3` and ruby `v3.0.2`) then running

1. `bundle install --without production`
2. `rails db:migrate`
3. `rails test`

I get AppMaps, and I get a bunch of findings, but they're not showing up in the `Runtime Analysis` tree:

image

As you can see, there are a bunch of findings listed on the `Runtime Analysis` instructions page and in the `Problems` tab, but they're not in the tree view. There are just a bunch of failed tests listed.

Opening the same project in VS Code yields:

image

**Comment by jansorg** [comment]
@ahtrotta Does closing and reopening the project help?

**Comment by ahtrotta** [comment]
> @ahtrotta Does closing and reopening the project help?

No, there are still no findings, just failed tests.

**Comment by jansorg** [comment]
Could you attach a zip of the generated AppMaps, please?

**Comment by jansorg** [comment]
> > * [ ]   Do I have to deduplicate findings before applying the grouping or only the findings inside a single rule group?
> 
> Either way should be fine as long as you're using `hash_v2` to de-duplicate. How is it implemented currently?

Deduplication is using the hash and is done for each group of findings, i.e. for groups of impact domains:
https://github.com/getappmap/appmap-intellij-plugin/blob/6e765db13bc81a4d96dfa66dec7fc17ac80be7ea/plugin-core/src/main/java/appland/toolwindow/runtimeAnalysis/nodes/FindingsGroupNode.java#L56
 
> > * [ ]   ["Runtime Analysis panel" should display a tree #328 (comment)](https://github.com/getappmap/appmap-intellij-plugin/issues/328#issuecomment-1682423415) Should I add the additional group inside "Failed tests"?
> 
> The `failed tests` group in VS Code is for the `AppMap` toolbar, not the `Runtime Analysis` toolbar, so I think this should be implemented in a separate batch of work.

Thanks, I missed that.

**Comment by jansorg** [comment]
@ahtrotta Please try again. The issue was, that findings of AppMaps with "test_status: failed" were not displayed below "Findings". I was following the comment at https://github.com/getappmap/appmap-intellij-plugin/issues/328#issuecomment-1682477514, but that obviously doesn't match VSCode. I've pushed https://github.com/getappmap/appmap-intellij-plugin/pull/358/commits/80c06af7ea0e2b2cbfa8b540b6fef824a77ca822 to fix this and to match VSCode.

**Pull request merged**
